### ISSUE TITLE
Failed Synchronization

### ISSUE THREAD

**Issue by manuelswd** [pronamic/wp-woocommerce-stock-synchronization#10]
Hi,

I'm testing the plugin trying to sync two product with the same SKU. I followed all the instruction reported in the documentation, but in both store the log return me this message Failed - Synchronization to: https://my-site1.com/ (response code: 200, error: ) and Failed - Synchronization to: https://my-site2.com/ (response code: 200, error: )

Checking out the code seems that the variable that should contain the data is empty for some reason.

Thanks in advance for the support

**Comment by rvdsteege** [comment]
Sounds like an issue with your WordPress/hosting environment. For assistance with this issue, please use the form at https://www.pronamic.eu/contact/ and make sure to enter a valid license key.
