### ISSUE TITLE
Notice: Undefined property: Pronamic_WP_WC_StockSyncSynchronizer::$process_sync

### ISSUE THREAD

**Issue by dademaru** [pronamic/wp-woocommerce-stock-synchronization#5]
Hi,
enabling DEBUG I get this notice:
Notice: Undefined property: Pronamic_WP_WC_StockSyncSynchronizer::$process_sync in /mypath/wp-content/plugins/woocommerce-stock-synchronization/classes/class-synchronizer.php on line 166

Is it possible to fix it?
Thanks

**Comment by rvdsteege** [comment]
Fixed (long time ago ;)) in https://github.com/pronamic/wp-woocommerce-stock-synchronization/commit/ff0cdfa51f7c442c88277e13f1a55bcce34564e6
